In [1]:
import requests
from bs4 import BeautifulSoup
import pandas

r=requests.get("https://www.century21.com/real-estate/california-md/LCMDCALIFORNIA/", headers={'User-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0'})
c=r.content

soup=BeautifulSoup(c, "html.parser")

all=soup.find_all("div", {"class":"property-card-primary-info"})

In [2]:
l=[]
for item in all:
    d={}
    try:
        d["Price"]=item.find("a", {"class":"listing-price"}).text.strip()
    except:
        d["Price"]=None
        
    try:
        d["Address"]=item.find("div", {"class":"property-address"}).text.strip()
    except:
        d["Address"]=None
    
    try:
        d["City"]=item.find("div", {"class":"property-city"}).text.strip()
    except:
        d["City"]=None
    
    try:
        d["Bed"]=item.find("div", {"class":"property-beds"}).find("strong").text.strip()
    except:
        d["Bed"]=None
    
    try:
        d["Bath"]=item.find("div", {"class":"property-baths"}).find("strong").text.strip()
    except:
        d["Bath"]=None
    
    try:
        d["Sqft"]=item.find("div", {"class":"property-sqft"}).find("strong").text.strip()
    except:
        d["Sqft"]=None
    
    l.append(d)

In [3]:
df=pandas.DataFrame(l)

In [4]:
df

,Price,Address,City,Bed,Bath,Sqft
0,"$865,000",23731 Kingston Creek,California MD 20619,4,2,"1,823"
1,"$385,000",23165 Heatherwood Lane,California MD 20619,3,2,"1,642"
2,"$79,900",45275 F Birch Lane,California MD 20619,None,None,None
3,"$405,000",23242 Windflower Way,California MD 20619,4,3,"2,737"
4,"$250,000",22616 Old Rolling,California MD 20619,3,2,"1,170"
5,"$175,000",44693 White Oak Court APT#515,California MD 20619,2,1,960
6,"$549,900",23323 Sawara Ct.,California MD 20619,5,3,None
7,"$475,000",43992 Swift Fox Drive,California MD 20619,4,3,"3,374"
8,"$135,000",23244 Chestnut Oak Court 1F,California MD 20619,1,1,759
9,"$154,900",23140 Cobblestone Ln #306 Cobblestone Ln #306,California MD 20619,2,2,"1,178"
10,"$79,900",22146 Indian Bridge,California MD 20619,None,None,None
11,"$260,000",23570 F D R Boulevard 309,California MD 20619,2,2,"1,431"
12,"$370,000",43943 Eucalyptus Way,California MD 20619,3,3,"2,200"
13,"$365,000",23560 Gross Drive,California MD 20619,4,2,"2,339"
14,"$534,900",45238 Woodhaven Drive,California MD 20619,4,3,"4,226"
15,"$537,000",45242 Woodhaven Drive,California MD 20619,4,3,"3,690"
16,"$337,000",23325 Laurel Hill Dr.,California MD 20619,3,2,None
17,"$885,000",23678 Max Way,California MD 20619,2,1,740
18,"$439,000",43967 Swift Fox Drive,California MD 20619,3,3,"2,895"
19,"$565,000",23775 Kingston Village Road,California MD 20619,3,2,"1,744"

In [5]:
df.to_csv("Output.csv")